const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Shape3D,
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Physics,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.SetFontColor
	];
};
self.C3_JsPropNameTable = [
	{Pl: 0},
	{Mosaico: 0},
	{Sprite: 0},
	{Sólido: 0},
	{PularAtravés: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{SoldierIdle: 0},
	{Plataforma: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Keyboard: 0},
	{sp10: 0},
	{Sprite11: 0},
	{Texto: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Texto2: 0},
	{Sprite10: 0},
	{Sprite16: 0},
	{Texto3: 0},
	{sp11: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{sp12: 0},
	{moeda3: 0},
	{espinhos3: 0},
	{evento001: 0},
	{espinho4: 0},
	{sp13: 0},
	{moeda4: 0},
	{Física: 0},
	{espinhos5: 0},
	{sp14: 0},
	{sp15: 0},
	{Sprite19: 0},
	{sp16: 0},
	{Texto4: 0},
	{botao: 0},
	{Texto5: 0},
	{espinho6: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{moeda: 0}
];

self.InstanceType = {
	Pl: class extends self.I3DShapeInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	SoldierIdle: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	sp10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	sp11: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	sp12: class extends self.ISpriteInstance {},
	moeda3: class extends self.ISpriteInstance {},
	espinhos3: class extends self.ISpriteInstance {},
	evento001: class extends self.ISpriteInstance {},
	espinho4: class extends self.ISpriteInstance {},
	sp13: class extends self.ISpriteInstance {},
	moeda4: class extends self.ISpriteInstance {},
	espinhos5: class extends self.ISpriteInstance {},
	sp14: class extends self.ISpriteInstance {},
	sp15: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	sp16: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	botao: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	espinho6: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {}
}